"use client";

// Phosphor Icons — Client Component Wrappers para uso em Server Components
// Importe desse arquivo ao invés de @phosphor-icons/react diretamente em Server Components
export {
    Scales,
    CurrencyDollar,
    CalendarBlank,
    CheckSquare,
    Handshake,
    WarningCircle,
    ArrowRight,
    ArrowLeft,
    Sparkle,
    CheckCircle,
    Clock,
    Bell,
    BellRinging,
    User,
    Gear,
    SignOut,
    MagnifyingGlass,
    Sun,
    Moon,
    CaretDown,
    CaretRight,
    CaretLeft,
    SquaresFour,
    UsersThree,
    Newspaper,
    ChatCircle,
    Robot,
    Target,
    FileText,
    ChartLine,
    ChartBar,
    Calendar,
    XCircle,
    Info,
    Warning,
    SealCheck,
    X,
    Plus,
    DotsThree,
    Funnel,
    Export,
    Upload,
    DownloadSimple,
    Eye,
    PencilSimple,
    Trash,
    MagnifyingGlassPlus,
    Phone,
    Envelope,
    MapPin,
    Buildings,
    BriefcaseMetal,
    ChartPieSlice,
    CurrencyBtc,
    Tag,
    Timer,
    Flag,
    TrendDown,
    TrendUp,
    CircleNotch,
    Suitcase,
    Users,
} from "@phosphor-icons/react";
